# Generated by Django 5.1.1 on 2024-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancemetrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
    ]
