# Generated by Django 5.1.1 on 2024-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancemetrics', '0002_alter_performance_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='last_test_score',
            field=models.FloatField(default=0.0),
        ),
    ]
