# Generated by Django 5.1.1 on 2024-10-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancemetrics', '0003_alter_performance_last_test_score'),
        ('quiz', '0002_remove_response_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='quiz.test'),
        ),
    ]
