# Generated by Django 5.1.1 on 2024-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancemetrics', '0005_alter_performance_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
