# Generated by Django 5.1.1 on 2024-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='cours_fichiers/'),
        ),
    ]
