# Generated by Django 5.1.1 on 2024-10-30 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
